Add battery gauge display
democloid/picoTracker pull request #127
Opened 2024-02-14 11:12 UTC by maks

This adds a simple battery gauge display.

For now its only using the previously existing (unused) battery display functionality: so only on the Song screen and only updated every beat only when project is playing back.

The voltage levels used for each "state" of the gauge were determined approximately based on a run down test (timelapse video below).

The intention is to iterate on this in followup PRs to use better mechanism for scheduling reading batt level updates, show gauge on all screens, define a new "CD_ERROR" colour for use when batt level critical and improve the ascii art of the gauge display.

The current state of the gauge UI is:

![batt-gauge](https://github.com/democloid/picoTracker/assets/71999/22f933e1-0da3-4077-996c-97b1d2cc9d8f)

https://github.com/democloid/picoTracker/assets/71999/67a114db-2435-4ef6-b4e2-bc895244b924

2024-02-14 14:34 UTC, democloid commented
Nice, Is the time lapse from higher to lower? by each "state" of the gauge you mean that the values that you read from the ADC doesn't necessarily correspond to actual meaningful numbers that you could directly display? Keep in mind that max charge for LiPo batteries is around 4.2V, not 3.7V. I'd say 3.7V is when you're running low already. 

As for location, we'd probably need to find a better place for it, maybe a single char at the top upper corner with some custom chars.

2024-02-14 21:19 UTC, maks commented
> Nice, Is the time lapse from higher to lower? by each "state" of the gauge you mean that the values that you read from the ADC doesn't necessarily correspond to actual meaningful numbers that you could directly display? Keep in mind that 

@democloid Yes the time lapse runs from about a min after turning on from fully charged state (bit of faffing around setting up the recording) until the end when the pico turned off.
So for the time lapse, I had the display just showing a string of the value taken from the ADC and then multiplied by 0.8(mV) and then x2 (because of voltage divider).

>max charge for LiPo batteries is around 4.2V, not 3.7V. I'd say 3.7V is when you're running low already.

Actually [according to this article thats not the case](https://learn.adafruit.com/li-ion-and-lipoly-batteries/voltages) 4.2V is just is an initial postcharging temporary max and 3.7 is the nominal voltage and that is infact pretty much what I observed experimentally, the timelapse shows decent correlation to the green discharge curve on the diagram in that article.
I'll try to make time to run the test again and would be happy for others to as well, but for now the voltage levels I picked for each "state" (number of "+" chars shown) corresponds to the experimentally observed levels of "fully charged" "mostly charged", "low" and "critical" levels.

> As for location, we'd probably need to find a better place for it, maybe a single char at the top upper corner with some custom chars.

Agreed! I would be great to have a nicer UI but I think given how important the batt level is (even the very approximate one we currently have) it would be good for it to be more prominent than a single char and for me more asthetically pleasing :-)

2024-02-17 22:12 UTC, maks commented
@democloid are you ok to merge this and then look at changing the layout and design of the gauge in follow up PRs?

2024-02-27 17:03 UTC, democloid requested changes

2024-02-29 10:47 UTC, maks commented on sources/Adapters/picoTracker/system/picoTrackerSystem.cpp
> +  unsigned int beatCount = SyncMaster::GetInstance()->GetBeatCount();
Yes it is but it was just a temporary means until the 1hz callback was implemented in the follow on PR and there it was removed when the 1Hz callback was added so will keep it here as that PR removes it.

2024-02-29 10:50 UTC, maks commented on sources/Adapters/picoTracker/system/picoTrackerSystem.cpp
> +  int lastBattLevel_ = -1;
this was also just temporary and removed in following PR once the 1Hz callback was available for use.

2024-02-29 10:52 UTC, maks commented
@democloid this is ready now for re-review, left comment about couple of places I didnt change as they are covered by a follow on PR.

2024-02-29 14:42 UTC, democloid approved these changes

2024-02-29 22:01 UTC, merged