Show flash usage
democloid/picoTracker pull request #136
Opened 2024-02-18 10:09 UTC by maks

This adds a "statusbar" at the bottom of the sample import screen that shows the size of the currently selected file and the total remaining space in Flash storage for the current project, formated to B, KB or MB.

The free amount will update as samples are imported into the project.

Also there could probably be a bit of tidy up in `picoTrackerPagedDir` to factor out opening a dir into a separate private method as this code has now been copy/pasted a couple of times into diff places in the class.

Note during testing this uncovered an existing bug where some file list entries are incorrectly being assigned the "parent dir" type, but that will be fixed in a separate PR.

![PXL_20240218_100243659](https://github.com/democloid/picoTracker/assets/71999/e91852b6-7dfc-4efe-b9c0-6bef21657cd4)

2024-02-18 10:21 UTC, maks commented
@democloid also completely open to suggestions for better labels for the UI :-)

2024-02-27 05:32 UTC, democloid requested changes

2024-02-29 10:36 UTC, maks commented on sources/Application/Views/ModalDialogs/PagedImportSampleDialog.cpp
> +  char *unitsFormatted = (char *)malloc(sizeof(char) * 10);
Done: changed to use ETL strings for the string buffers here.

2024-03-01 01:53 UTC, democloid approved these changes

2024-03-01 02:24 UTC, merged