Set status to Importing dir when importing samples
democloid/picoTracker pull request #92
Opened 2024-01-22 05:30 UTC by shockdesign

Shows a status message when importing samples to avoid the delay before it actually starts loading the samples.

Related to https://github.com/democloid/picoTracker/issues/40

2024-01-22 11:11 UTC, maks requested changes

2024-01-22 11:11 UTC, maks commented on sources/Application/Instruments/SamplePool.cpp
> +  Status::Set("Importing %s", path.GetName().c_str());
Now that this has been moved up here, can probably remove the now redundant identical code on line 163 ?

2024-01-25 06:12 UTC, shockdesign commented
@maks have updated as per your suggestion.

2024-01-25 08:54 UTC, maks approved these changes
nice one! 👍🏻 
just tested it and makes a big difference having the loading message show without a delay.

2024-01-25 15:16 UTC, merged